
export type LessonStep = {
  id: string;
  type: 'content' | 'explore' | 'concept' | 'challenge' | 'mapping';
  title: string;
  description: string;
  content?: string;
  pdfLabel?: string;
  pdfUrl?: string;
  allowedBlocks?: string[];
  challengeBlocks?: string[];
  simulationId?: string;
  explorationSimulationId?: string;
  challengeSimulationId?: string;
  mappingSimulationId?: string;
  mappingCodeComponent?: string;
  showSerialOutput?: boolean;
  challengeStrict?: boolean;
  challengePinValues?: Record<string, number>;
  hint?: string;
};

export type Lesson = {
  id: string;
  title: string;
  description: string;
  icon: string;
  estimatedMinutes: number;
  steps: LessonStep[];
};

export type Level = {
  id: number;
  title: string;
  description: string;
  icon: string;
  isLocked: boolean;
  lessons: Lesson[];
};

export const LEVELS: Level[] = [
  {
    id: 1,
    title: 'ESP32 Fundamentals',
    description: 'Build confidence with the core concepts behind digital output and timing.',
    icon: '🟢',
    isLocked: false,
    lessons: [
      {
        id: '1-1',
        title: 'Your First Blink',
        description: 'Control a basic LED sequence with proper setup and timing.',
        icon: '💡',
        estimatedMinutes: 20,
        steps: [
          {
            id: 'intro',
            type: 'content',
            title: 'Introduction',
            description: 'Learn the basics of LED control and how sensors read the world',
          },
          {
            id: 'explore',
            type: 'explore',
            title: 'Exploration',
            description: 'Try turning the LED on and off',
            allowedBlocks: ['dw_high', 'dw_low', 'pinMode'],
          },
          {
            id: 'concept',
            type: 'concept',
            title: 'Concept Building',
            description: 'Why microcontrollers need delays',
          },
          {
            id: 'challenge',
            type: 'challenge',
            title: 'Student Task',
            description: 'Build a proper blinking LED program',
            allowedBlocks: ['pinMode', 'dw_high', 'dw_low'],
            challengeBlocks: ['pinMode', 'dw_high', 'dw_low'],
            simulationId: 'missing-delay',
            challengeStrict: false,
            hint: 'Set the pin mode first, then turn the LED on, then turn it off',
          },
          {
            id: 'mapping',
            type: 'mapping',
            title: 'Arduino Mapping',
            description: 'See how your blocks become real C++ code',
          },
        ],
      },
      {
        id: '1-2',
        title: 'Making Changes Visible (Using Delays)',
        description: 'Understand timing control for smooth and readable behavior.',
        icon: '⏱️',
        estimatedMinutes: 15,
        steps: [
          {
            id: 'intro',
            type: 'content',
            title: 'Introduction',
            description: 'Learn how timing changes program behavior',
          },
          {
            id: 'explore',
            type: 'explore',
            title: 'Exploration',
            description: 'Experiment with short and long delays on LED output',
            allowedBlocks: ['pinMode', 'dw_high', 'dw_low', 'delay_ms', 'delay_sec'],
          },
          {
            id: 'concept',
            type: 'concept',
            title: 'Concept Building',
            description: 'Blocking delays vs responsive loops',

          },
          {
            id: 'challenge',
            type: 'challenge',
            title: 'Student Task',
            description: 'Build a proper blinking LED program with delays',
            allowedBlocks: ['pinMode', 'dw_high', 'dw_low', 'delay_ms', 'delay_sec'],
            challengeBlocks: ['pinMode', 'dw_high', 'delay_ms', 'dw_low', 'delay_ms'],
            simulationId: 'led-delay',
            challengeStrict: false,
            hint: 'Set the pin mode, turn the LED on, wait, turn it off, then wait again',
          },
          {
            id: 'mapping',
            type: 'mapping',
            title: 'Arduino Mapping',
            description: 'See how your blocks become real C++ code',
          },
        ],
      },
      {
        id: '1-3',
        title: 'What Just Happened?',
        description: 'Understanding sequential execution and state',
        icon: '🔁',
        estimatedMinutes: 20,
        steps: [
          {
            id: 'intro',
            type: 'content',
            title: 'Introduction',
            description: 'How the ESP32 follows your instructions',
          },
          {
            id: 'explore',
            type: 'explore',
            title: 'Exploration',
            description: 'Watch the execution cycle in action',
            explorationSimulationId: 'cycle-timeline',
          },
          {
            id: 'concept',
            type: 'concept',
            title: 'Concept Building',
            description: 'Sequential execution, state, and order',
          },
          {
            id: 'challenge',
            type: 'challenge',
            title: 'Student Task',
            description: 'Build your own loop and observe the behavior',
            challengeSimulationId: 'infinite-loop',
            allowedBlocks: ['pinMode', 'dw_high', 'dw_low', 'delay_ms'],
            challengeBlocks: ['pinMode', 'dw_high', 'dw_low'],
            challengeStrict: false,
            hint: 'Try different block orders and observe how the LED behavior changes',
          },
          {
            id: 'mapping',
            type: 'mapping',
            title: 'Arduino Mapping',
            description: 'See how your blocks become real C++ code',
          },
        ],
      },
      {
        id: '1-4',
        title: 'Understanding Program Flow',
        description: 'How Setup and Loop structure every ESP32 program',
        icon: '⚙️',
        estimatedMinutes: 20,
        steps: [
          {
            id: 'intro',
            type: 'content',
            title: 'Introduction',
            description: 'Why does the program repeat automatically?',
          },
          {
            id: 'explore',
            type: 'explore',
            title: 'Exploration',
            description: 'Spot the difference between Setup and Loop',
            explorationSimulationId: 'setup-vs-loop',
          },
          {
            id: 'concept',
            type: 'concept',
            title: 'Concept Building',
            description: 'Setup runs once. Loop runs forever.',
          },
          {
            id: 'challenge',
            type: 'challenge',
            title: 'Student Task',
            description: 'Build a program that blinks an LED continuously',
            allowedBlocks: ['pinMode', 'dw_high', 'dw_low', 'delay_ms'],
            challengeBlocks: ['pinMode', 'dw_high', 'delay_ms', 'dw_low', 'delay_ms'],
            challengeStrict: false,
            simulationId: 'program-flow',
            hint: 'Make sure to set the pin mode, then turn the LED on and off with delays in between',
          },
          {
            id: 'mapping',
            type: 'mapping',
            title: 'Arduino Mapping',
            description: 'See how your blocks map to setup() and loop()',
          },
        ],
      },
    ],
  },
  {
    id: 2,
    title: 'Output & Communication',
    description: 'Learn how to send data, read sensors, and communicate between your ESP32 and the world.',
    icon: '📡',
    isLocked: false,
    lessons: [
      {
        id: '2-1',
        title: 'Seeing Output',
        description: 'Make the ESP32 send messages using Serial communication',
        icon: '📟',
        estimatedMinutes: 20,
        steps: [
          {
            id: 'intro',
            type: 'content',
            title: 'Introduction',
            description: 'How the ESP32 communicates with your computer',
          },
          {
            id: 'explore',
            type: 'explore',
            title: 'Exploration',
            description: 'Watch data flow from blocks to Serial Monitor',
            explorationSimulationId: 'serial-explorer',
          },
          {
            id: 'concept',
            type: 'concept',
            title: 'Concept Building',
            description: 'Serial communication, output, and debugging',
          },
          {
            id: 'challenge',
            type: 'challenge',
            title: 'Student Task',
            description: 'Create your first Serial output program',
            allowedBlocks: ['serial_begin', 'serial_print', 'delay_ms', 'delay_sec'],
            challengeBlocks: ['serial_begin', 'serial_print', 'delay_ms'],
            challengeStrict: false,
            simulationId: 'serial-monitor',
            showSerialOutput: true,
            hint: 'Start Serial first, then print your message, then add a delay',
          },
          {
            id: 'mapping',
            type: 'mapping',
            title: 'Arduino Mapping',
            description: 'See how your blocks become Serial communication code',
            showSerialOutput: true,
          },
        ],
      },
      {
        id: '2-2',
        title: 'Variables',
        description: 'Store, update, and use values in your program',
        icon: '📦',
        estimatedMinutes: 25,
        steps: [
          {
            id: 'intro',
            type: 'content',
            title: 'Introduction',
            description: 'How programs remember and update information',
          },
          {
            id: 'explore',
            type: 'explore',
            title: 'Exploration',
            description: 'Create variables and watch how values are stored and updated',
            explorationSimulationId: 'variable-box',
          },
          {
            id: 'concept',
            type: 'concept',
            title: 'Concept Building',
            description: 'Variable types, storage, and updating values',
          },
          {
            id: 'challenge',
            type: 'challenge',
            title: 'Student Task',
            description: 'Build a counter that increments and prints to Serial Monitor',
            allowedBlocks: ['var_int', 'var_add', 'serial_begin', 'serial_printvar', 'serial_println', 'delay_ms', 'delay_sec'],
            challengeBlocks: ['var_int', 'serial_begin', 'serial_printvar', 'var_add', 'delay_ms'],
            challengeStrict: false,
            simulationId: 'counter',
            showSerialOutput: true,
            hint: 'Important: the variable name in var_int, var_add, and serial_printvar must all match exactly. Create a variable first, start Serial, print the variable, then add to it, then delay',
          },
          {
            id: 'mapping',
            type: 'mapping',
            title: 'Arduino Mapping',
            description: 'See how variables and Serial output become real C++ code',
            showSerialOutput: true,
          },
        ],
      },
      {
        id: '2-3',
        title: 'Introducing Inputs',
        description: 'Use a button to send signals to your ESP32',
        icon: '🔘',
        estimatedMinutes: 25,
        steps: [
          {
            id: 'intro',
            type: 'content',
            title: 'Introduction',
            description: 'How external devices send signals to the ESP32',
          },
          {
            id: 'explore',
            type: 'explore',
            title: 'Exploration',
            description: 'See how a button press becomes an electrical signal',
            explorationSimulationId: 'button-signal',
          },
          {
            id: 'concept',
            type: 'concept',
            title: 'Concept Building',
            description: 'Inputs, signals, and reading pin states',
          },
          {
            id: 'challenge',
            type: 'challenge',
            title: 'Student Task',
            description: 'Read a button and display its state on the Serial Monitor',
            allowedBlocks: ['btn_read', 'serial_begin', 'serial_print', 'serial_printvar', 'delay_ms', 'delay_sec'],
            challengeBlocks: ['btn_read', 'serial_begin', 'serial_printvar', 'delay_ms'],
            challengeStrict: false,
            simulationId: 'button-monitor',
            showSerialOutput: true,
            hint: 'Read the button into a variable first, start Serial, then print that variable — make sure the variable name matches in both blocks',
          },
          {
            id: 'mapping',
            type: 'mapping',
            title: 'Arduino Mapping',
            description: 'See how button reading becomes real C++ code',
            mappingSimulationId: 'signal-analyzer',
            mappingCodeComponent: 'button',
          },
        ],
      },
      {
        id: '2-4',
        title: 'Making Decisions',
        description: 'Use IF logic to control outputs based on input',
        icon: '🔀',
        estimatedMinutes: 25,
        steps: [
          {
            id: 'intro',
            type: 'content',
            title: 'Introduction',
            description: 'How the ESP32 chooses between different actions',
          },
          {
            id: 'explore',
            type: 'explore',
            title: 'Exploration',
            description: 'See how conditions create two possible paths',
            explorationSimulationId: 'decision-flow',
          },
          {
            id: 'concept',
            type: 'concept',
            title: 'Concept Building',
            description: 'IF conditions, TRUE/FALSE evaluation, branching',

          },
          {
            id: 'challenge',
            type: 'challenge',
            title: 'Student Task',
            description: 'Control an LED using a button and IF condition',
            allowedBlocks: ['btn_read', 'pinMode', 'dw_high', 'dw_low', 'if_block', 'else_block', 'end_if'],
            challengeBlocks: ['btn_read', 'if_block', 'dw_high', 'else_block', 'dw_low', 'end_if'],
            challengeStrict: false,
            simulationId: 'if-decision',
            hint: 'Read the button into btnState, then use if_block with condition "btnState == HIGH", place dw_high inside IF and dw_low inside ELSE, close with end_if',
          },
          {
            id: 'mapping',
            type: 'mapping',
            title: 'Arduino Mapping',
            description: 'See how IF logic becomes real C++ code',
            mappingSimulationId: 'if-decision',
            mappingCodeComponent: 'if',
          },
        ],
      },
    ],
  },
  {
    id: 3,
    title: 'Analog Input & PWM',
    description: 'Read continuous values from sensors and control outputs like LED brightness and motor speed with precision.',
    icon: '🟡',
    isLocked: false,
    lessons: [
      {
        id: '3-1',
        title: 'Reading Changing Values',
        description: 'Read analog inputs from photoresistors and potentiometers to measure continuous variation.',
        icon: '📊',
        estimatedMinutes: 20,
        steps: [
          {
            id: 'intro',
            type: 'content',
            title: 'Introduction',
            description: 'Learn how to read changing values (analog input)',
          },
          {
            id: 'explore',
            type: 'explore',
            title: 'Exploration',
            description: 'Connect a photoresistor and potentiometer and read their values',
            explorationSimulationId: 'analog-oscilloscope',
            allowedBlocks: ['analog_read', 'serial_begin', 'serial_printvar', 'delay_ms'],
          },
          {
            id: 'concept',
            type: 'concept',
            title: 'Concept Building',
            description: 'Understand analog sensors, voltages, and digital range',
          },
          {
            id: 'challenge',
            type: 'challenge',
            title: 'Student Task',
            description: 'Build a dual sensor reader program',
            allowedBlocks: ['analog_read', 'serial_begin', 'serial_printvar', 'delay_ms'],
            challengeBlocks: ['serial_begin', 'analog_read', 'serial_printvar', 'analog_read', 'serial_printvar', 'delay_ms'],
            simulationId: 'dual-sensor',
            showSerialOutput: true,
            hint: 'In loop, read light sensor (Pin 34) into lightVal and potentiometer (Pin 35) into potVal. Print both to Serial Monitor.',
          },
          {
            id: 'mapping',
            type: 'mapping',
            title: 'Arduino Mapping',
            description: 'See how analogRead maps to real C++ code',
            mappingSimulationId: 'dual-sensor',
            mappingCodeComponent: 'analog',
            showSerialOutput: true,
          },
        ],
      },
      {
        id: '3-2',
        title: 'Controlling Intensity (PWM)',
        description: 'Fade LEDs and control analog outputs beyond digital ON/OFF using PWM.',
        icon: '🔆',
        estimatedMinutes: 20,
        steps: [
          {
            id: 'intro',
            type: 'content',
            title: 'Introduction',
            description: 'Learn to adjust LED brightness using Pulse Width Modulation (PWM)',
          },
          {
            id: 'explore',
            type: 'explore',
            title: 'Exploration',
            description: 'Observe the PWM wave form and adjust the duty cycle',
            explorationSimulationId: 'pwm-wave',
            allowedBlocks: ['pwm_setup', 'pwm_write', 'delay_ms'],
          },
          {
            id: 'concept',
            type: 'concept',
            title: 'Concept Building',
            description: 'Learn about duty cycles, frequencies, and analogWrite',
          },
          {
            id: 'challenge',
            type: 'challenge',
            title: 'Student Task',
            description: 'Control LED brightness with a potentiometer',
            allowedBlocks: ['analog_read', 'pwm_setup', 'pwm_write', 'delay_ms'],
            challengeBlocks: ['pwm_setup', 'analog_read', 'pwm_write', 'delay_ms'],
            simulationId: 'sensor-brightness',
            hint: 'Set up PWM on Pin 2 first. In loop, read analog Pin 35 into potVal, then set Pin 2 brightness to potVal.',
          },
          {
            id: 'mapping',
            type: 'mapping',
            title: 'Arduino Mapping',
            description: 'See how PWM setup and write map to C++ code',
            mappingSimulationId: 'sensor-brightness',
            mappingCodeComponent: 'pwm',
          },
        ],
      },
      {
        id: '3-3',
        title: 'Translating Values (Mapping)',
        description: 'Translate input ranges (e.g. 0-4095) to output ranges (e.g. 0-255) using mathematics.',
        icon: '🗺️',
        estimatedMinutes: 20,
        steps: [
          {
            id: 'intro',
            type: 'content',
            title: 'Introduction',
            description: 'Understand why we need to match sensor ranges to outputs',
          },
          {
            id: 'explore',
            type: 'explore',
            title: 'Exploration',
            description: 'Interact with the interactive map block and observe mapping results',
            explorationSimulationId: 'mapping',
            allowedBlocks: ['map_val', 'delay_ms'],
          },
          {
            id: 'concept',
            type: 'concept',
            title: 'Concept Building',
            description: 'Learn the mathematical map() function and linear interpolation',
          },
          {
            id: 'challenge',
            type: 'challenge',
            title: 'Student Task',
            description: 'Map a potentiometer (0-4095) to an LED brightness (0-255)',
            allowedBlocks: ['analog_read', 'map_val', 'pwm_setup', 'pwm_write', 'delay_ms'],
            challengeBlocks: ['pwm_setup', 'analog_read', 'map_val', 'pwm_write', 'delay_ms'],
            simulationId: 'mapped-sensor',
            hint: 'Set up PWM on Pin 2. In loop, read Pin 35 into potVal. Map potVal from 0-4095 to 0-255 into brightness. Write brightness to Pin 2.',
          },
          {
            id: 'mapping',
            type: 'mapping',
            title: 'Arduino Mapping',
            description: 'See how map() and pwmWrite map to C++ code',
            mappingSimulationId: 'mapped-sensor',
            mappingCodeComponent: 'mapping',
          },
        ],
      },
      {
        id: '3-4',
        title: 'Real-Time Control System',
        description: 'Combine analog inputs, mapping, and logic to build intelligent responsive control systems.',
        icon: '⚙️',
        estimatedMinutes: 25,
        steps: [
          {
            id: 'intro',
            type: 'content',
            title: 'Introduction',
            description: 'Build responsive automatic control loops',
          },
          {
            id: 'explore',
            type: 'explore',
            title: 'Exploration',
            description: 'Observe real-time feedback loops and threshold actions',
            explorationSimulationId: 'realtime-control',
            allowedBlocks: ['analog_read', 'map_val', 'pwm_write', 'if_block', 'else_block', 'end_if', 'delay_ms'],
          },
          {
            id: 'concept',
            type: 'concept',
            title: 'Concept Building',
            description: 'Learn feedback loops, automated light controllers, and safety thresholds',
          },
          {
            id: 'challenge',
            type: 'challenge',
            title: 'Student Task',
            description: 'Build an automatic night light with adjustable override',
            allowedBlocks: ['pinMode', 'analog_read', 'map_val', 'pwm_setup', 'pwm_write', 'if_block', 'else_block', 'end_if', 'delay_ms'],
            challengeBlocks: ['pwm_setup', 'analog_read', 'map_val', 'pwm_write', 'delay_ms'],
            simulationId: 'dual-mode',
            hint: 'Read the light sensor on Pin 34. Map it to LED brightness. Then write the mapped value to PWM Pin 2.',
          },
          {
            id: 'mapping',
            type: 'mapping',
            title: 'Arduino Mapping',
            description: 'See how dual-mode feedback maps to C++ code',
            mappingSimulationId: 'dual-mode',
            mappingCodeComponent: 'dual-mode',
          },
        ],
      },
    ],
  },
  {
    id: 4,
    title: 'Control Structures',
    description: 'Master loops and logic to build dynamic, intelligent programs.',
    icon: '🔁',
    isLocked: false,
    lessons: [
      {
        id: '4-1',
        title: 'Repetition Structures',
        description: 'Use for loops to repeat actions a controlled number of times',
        icon: '🔁',
        estimatedMinutes: 20,
        steps: [
          {
            id: 'intro',
            type: 'content',
            title: 'Introduction',
            description: 'Controlled repetition using for loops',
          },
          {
            id: 'explore',
            type: 'explore',
            title: 'Exploration',
            description: 'See why loops exist — manual code vs for loop',
            explorationSimulationId: 'for-loop-concept',
          },
          {
            id: 'concept',
            type: 'concept',
            title: 'Concept Building',
            description: 'For loop structure, counter, condition, and increment',
          },
          {
            id: 'challenge',
            type: 'challenge',
            title: 'Student Task',
            description: 'Blink an LED a fixed number of times using a for loop',
            allowedBlocks: ['pinMode', 'for_loop', 'dw_high', 'delay_ms', 'dw_low', 'end_loop'],
            challengeBlocks: ['pinMode', 'for_loop', 'dw_high', 'delay_ms', 'dw_low', 'end_loop'],
            challengeStrict: false,
            simulationId: 'for-loop-chaser',
            hint: 'Set pinMode first, then add for_loop with your repeat count, place dw_high + delay + dw_low inside, close with end_loop',
          },
          {
            id: 'mapping',
            type: 'mapping',
            title: 'Arduino Mapping',
            description: 'See how a for loop becomes real C++ code',
            mappingSimulationId: 'for-loop-chaser',
            mappingCodeComponent: 'for-loop',
          },
        ],
      },
      {
        id: '4-2',
        title: 'Conditional Repetition',
        description: 'Use while loops to repeat actions based on a condition',
        icon: '🔄',
        estimatedMinutes: 20,
        steps: [
          {
            id: 'intro',
            type: 'content',
            title: 'Introduction',
            description: 'Repeating while a condition remains true',
          },
          {
            id: 'explore',
            type: 'explore',
            title: 'Exploration',
            description: 'Feel the difference between for loops and while loops',
            explorationSimulationId: 'while-vs-for',
          },
          {
            id: 'concept',
            type: 'concept',
            title: 'Concept Building',
            description: 'While loop structure, condition checking, and variable-driven termination',
          },
          {
            id: 'challenge',
            type: 'challenge',
            title: 'Student Task',
            description: 'Blink an LED using a while loop with a countdown counter',
            allowedBlocks: ['var_int', 'pinMode', 'while_loop', 'dw_high', 'delay_ms', 'dw_low', 'var_add', 'end_loop'],
            challengeBlocks: ['var_int', 'while_loop', 'dw_high', 'delay_ms', 'dw_low', 'var_add', 'end_loop'],
            challengeStrict: false,
            simulationId: 'countdown',
            hint: 'Create a var_int named counter starting at 5, use while_loop with condition counter > 0, blink LED inside, then use var_add to subtract 1 from counter, close with end_loop',
          },
          {
            id: 'mapping',
            type: 'mapping',
            title: 'Arduino Mapping',
            description: 'See how a while loop countdown becomes real C++ code',
            mappingSimulationId: 'countdown',
            mappingCodeComponent: 'while-loop',
          },
        ],
      },
      {
        id: '4-3',
        title: 'Combining Logic',
        description: 'Use loops and conditions together for real-time interactive systems',
        icon: '🧠',
        estimatedMinutes: 25,
        steps: [
          {
            id: 'intro',
            type: 'content',
            title: 'Introduction',
            description: 'Loops and IF conditions working together',
          },
          {
            id: 'explore',
            type: 'explore',
            title: 'Exploration',
            description: 'Watch how a loop and condition flow together in real time',
            explorationSimulationId: 'signal-tree',
          },
          {
            id: 'concept',
            type: 'concept',
            title: 'Concept Building',
            description: 'Nested logic, real-time monitoring, and combined control',
          },
          {
            id: 'challenge',
            type: 'challenge',
            title: 'Student Task',
            description: 'Control LED blinking using a button and IF condition inside loop',
            allowedBlocks: ['btn_read', 'pinMode', 'if_block', 'dw_high', 'delay_ms', 'dw_low', 'else_block', 'end_if'],
            challengeBlocks: ['btn_read', 'if_block', 'dw_high', 'delay_ms', 'dw_low', 'else_block', 'dw_low', 'end_if'],
            challengeStrict: false,
            simulationId: 'if-decision',
            hint: 'Read the button into btnState, then use if_block with condition btnState == HIGH — place LED blink inside IF, dw_low inside ELSE, close with end_if',
          },
          {
            id: 'mapping',
            type: 'mapping',
            title: 'Arduino Mapping',
            description: 'See how loop + condition creates a real-time interactive system',
            mappingSimulationId: 'loop-condition',
            mappingCodeComponent: 'combined-logic',
          },
        ],
      },
      {
        id: '4-4',
        title: 'Pattern Systems',
        description: 'Build complex LED patterns using nested loops and logic',
        icon: '✨',
        estimatedMinutes: 30,
        steps: [
          {
            id: 'intro',
            type: 'content',
            title: 'Introduction',
            description: 'Creating patterns with complex control structures',
          },
          {
            id: 'explore',
            type: 'explore',
            title: 'Exploration',
            description: 'See how a loop condition controls which LEDs light up',
            explorationSimulationId: 'pattern-sequence',
          },
          {
            id: 'concept',
            type: 'concept',
            title: 'Concept Building',
            description: 'Using the loop counter as data inside the loop body',

          },
          {
            id: 'challenge',
            type: 'challenge',
            title: 'Student Task',
            description: 'Build a pattern system using a for loop and IF condition',
            allowedBlocks: ['pinMode', 'for_loop', 'if_block', 'dw_high', 'delay_ms', 'dw_low', 'else_block', 'end_if', 'end_loop'],
            challengeBlocks: ['for_loop', 'if_block', 'dw_high', 'end_if', 'end_loop'],
            challengeStrict: false,
            simulationId: 'pattern-chaser',
            hint: 'Add a for_loop block first, then place if_block inside it, put dw_high inside the IF, close with end_if then end_loop',
          },
          {
            id: 'mapping',
            type: 'mapping',
            title: 'Arduino Mapping',
            description: 'See how a for loop with IF condition generates a pattern in C++',
            mappingSimulationId: 'pattern-chaser',
            mappingCodeComponent: 'pattern',
          },
        ],
      },
    ],
  },
  {
    id: 5,
    title: 'Real-World Sensing',
    description: 'Read data from physical sensors and build reactive systems',
    icon: '📡',
    isLocked: false,
    lessons: [
      {
        id: '5-1',
        title: 'Temperature and Humidity',
        description: 'Read environmental data from a DHT11 sensor in real time',
        icon: '🌡️',
        estimatedMinutes: 20,
        steps: [
          {
            id: 'intro',
            type: 'content',
            title: 'Introduction',
            description: 'How the ESP32 reads data from the physical world',
          },
          {
            id: 'explore',
            type: 'explore',
            title: 'Exploration',
            description: 'Watch the DHT sensor read temperature and humidity live',
            explorationSimulationId: 'dht-environment',
          },
          {
            id: 'concept',
            type: 'concept',
            title: 'Concept Building',
            description: 'How sensors convert physical conditions into data',

          },
          {
            id: 'challenge',
            type: 'challenge',
            title: 'Student Task',
            description: 'Build an environmental monitor that reads and prints sensor data',
            allowedBlocks: ['dht_setup', 'serial_begin', 'dht_temp', 'dht_hum', 'serial_print', 'serial_println', 'serial_printvar', 'delay_ms'],
            challengeBlocks: ['dht_setup', 'dht_temp', 'dht_hum', 'serial_println'],
            challengeStrict: false,
            simulationId: 'dht-monitor',
            hint: 'Start with dht_setup, then read temperature and humidity into variables, then use serial_println to print both values',
          },
          {
            id: 'mapping',
            type: 'mapping',
            title: 'Arduino Mapping',
            description: 'See how DHT sensor blocks become real Arduino C++ code',
            mappingSimulationId: 'dht-monitor',
            mappingCodeComponent: 'dht',
          },
        ],
      },

      {
        id: '5-2',
        title: 'Motion Detection',
        description: 'Detect movement events using a PIR sensor',
        icon: '👁️',
        estimatedMinutes: 20,
        steps: [
          {
            id: 'intro',
            type: 'content',
            title: 'Introduction',
            description: 'Event-based sensing and how PIR sensors detect motion',

          },
          {
            id: 'explore',
            type: 'explore',
            title: 'Exploration',
            description: 'Move through the room and watch the PIR sensor react',
            explorationSimulationId: 'pir-explorer',
          },
          {
            id: 'concept',
            type: 'concept',
            title: 'Concept Building',
            description: 'Event-based signals vs continuous sensor values',

          },
          {
            id: 'challenge',
            type: 'challenge',
            title: 'Student Task',
            description: 'Build a motion-activated LED system using PIR sensor',
            allowedBlocks: ['pinMode', 'pir_read', 'if_block', 'else_block', 'end_if', 'dw_high', 'dw_low', 'serial_begin', 'serial_println', 'delay_ms'],
            challengeBlocks: ['pir_read', 'if_block', 'dw_high', 'dw_low', 'end_if'],
            challengeStrict: false,
            simulationId: 'pir-monitor',
            hint: 'Read the PIR sensor into a variable, then use if_block to check if it is HIGH — turn the LED on inside the IF and off in the else_block',
          },
          {
            id: 'mapping',
            type: 'mapping',
            title: 'Arduino Mapping',
            description: 'See how PIR motion detection maps to Arduino C++ code',
            mappingSimulationId: 'pir-autonomous',
            mappingCodeComponent: 'pir',
          },
        ],
      },
      {
        id: '5-3',
        title: 'Distance Measurement',
        description: 'Measure physical distance using an ultrasonic sensor',
        icon: '📏',
        estimatedMinutes: 20,
        steps: [
          {
            id: 'intro',
            type: 'content',
            title: 'Introduction',
            description: 'How ultrasonic sensors measure space using sound waves',

          },
          {
            id: 'explore',
            type: 'explore',
            title: 'Exploration',
            description: 'Move an object and watch distance values change in real time',
            explorationSimulationId: 'ultrasonic-explorer',
          },
          {
            id: 'concept',
            type: 'concept',
            title: 'Concept Building',
            description: 'From detection to measurement — understanding spatial awareness',

          },
          {
            id: 'challenge',
            type: 'challenge',
            title: 'Student Task',
            description: 'Build a distance monitoring system that reads and displays values',
            allowedBlocks: ['ultrasonic', 'serial_begin', 'serial_println', 'serial_printvar', 'delay_ms', 'if_block', 'else_block', 'end_if', 'dw_high', 'dw_low'],
            challengeBlocks: ['ultrasonic', 'serial_println'],
            challengeStrict: false,
            simulationId: 'ultrasonic-monitor',
            hint: 'Add the ultrasonic block first to read distance into a variable, then use serial_println to print it continuously',
          },
          {
            id: 'mapping',
            type: 'mapping',
            title: 'Arduino Mapping',
            description: 'See how the ultrasonic block maps to pulseIn and distance calculation in C++',
            mappingSimulationId: 'ultrasonic-autonomous',
            mappingCodeComponent: 'ultrasonic',
          },

        ],
      },
      {
        id: '5-4',
        title: 'Sound Output',
        description: 'Control a buzzer to produce sound signals based on sensor input',
        icon: '🔊',
        estimatedMinutes: 20,
        steps: [
          {
            id: 'intro',
            type: 'content',
            title: 'Introduction',
            description: 'How the ESP32 produces sound output using a buzzer',
          },
          {
            id: 'explore',
            type: 'explore',
            title: 'Exploration',
            description: 'Explore buzzer patterns and watch how timing shapes the signal',
            explorationSimulationId: 'buzzer-explorer',
          },
          {
            id: 'concept',
            type: 'concept',
            title: 'Concept Building',
            description: 'Sound as a pattern — how timing creates meaning in audio output',

          },
          {
            id: 'challenge',
            type: 'challenge',
            title: 'Student Task',
            description: 'Build a sound alert system triggered by PIR motion detection',
            allowedBlocks: ['pir_read', 'if_block', 'else_block', 'end_if', 'tone_on', 'tone_off', 'pinMode', 'delay_ms', 'serial_begin', 'serial_println'],
            challengeBlocks: ['pir_read', 'if_block', 'tone_on', 'tone_off', 'end_if'],
            challengeStrict: false,
            simulationId: 'buzzer-monitor',
            hint: 'Read the PIR sensor into a variable, use if_block to check if it is HIGH, put tone_on inside the IF and tone_off in the else_block',
          },
          {
            id: 'mapping',
            type: 'mapping',
            title: 'Arduino Mapping',
            description: 'See how buzzer control maps to tone() and noTone() in Arduino C++',
            mappingSimulationId: 'buzzer-autonomous',
            mappingCodeComponent: 'buzzer',
          },
        ],
      },
      {
        id: '5-5',
        title: 'Smart Sensor Systems',
        description: 'Combine multiple sensors to build intelligent decision-driven systems',
        icon: '🧠',
        estimatedMinutes: 25,
        steps: [
          {
            id: 'intro',
            type: 'content',
            title: 'Introduction',
            description: 'Why real systems rely on multiple sensors working together',
          },
          {
            id: 'explore',
            type: 'explore',
            title: 'Exploration',
            description: 'Combine PIR and ultrasonic inputs to see how decisions change',
            explorationSimulationId: 'smart-explorer',
          },
          {
            id: 'concept',
            type: 'concept',
            title: 'Concept Building',
            description: 'AND vs OR conditions — how combined logic creates intelligent behavior',
          },
          {
            id: 'challenge',
            type: 'challenge',
            title: 'Student Task',
            description: 'Build a smart alert system using PIR and ultrasonic sensors together',
            allowedBlocks: ['pir_read', 'ultrasonic', 'if_block', 'else_block', 'end_if', 'tone_on', 'tone_off', 'dw_high', 'dw_low', 'pinMode', 'serial_begin', 'serial_println', 'delay_ms'],
            challengeBlocks: ['pir_read', 'ultrasonic', 'if_block', 'end_if'],
            challengeStrict: false,
            simulationId: 'smart-monitor',
            hint: 'Read both sensors into variables first, then use if_block with both conditions — check motion AND distance together for the high alert case',
          },
          {
            id: 'mapping',
            type: 'mapping',
            title: 'Arduino Mapping',
            description: 'See how multi-sensor logic maps to AND conditions in Arduino C++',
            mappingSimulationId: 'smart-autonomous',
            mappingCodeComponent: 'smart-system',
          },
        ],
      },
    ],
  },
];